export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const REAUTHENTICATE_SUCCESS = 'REAUTHENTICATE_SUCCESS';